name: Maven build

on:
  workflow_call:
    inputs:
      service_dir:
        description: 'Path of service directory containing a valid java spring boot project'
        required: true
        type: string
      service_repository_url:
        description: 'ECR url'
        required: true
        type: string
      artifact_name:
        description: 'Artifact nam'
        required: true
        type: string
jobs:
 test:
    runs-on: ubuntu-latest
    container: maven:3-openjdk-11
    steps:
      - uses: actions/checkout@v2
      - run: cd ${{inputs.service_dir}} && mvn clean test
 build:
   runs-on: ubuntu-latest
   needs: test
   steps:
     - name: Set up Maven
       uses: stCarolas/setup-maven@v4.2
       with:
         maven-version: 3.8.2
     - name: Set up Docker Buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
     - uses: actions/checkout@v2
     - run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=${{inputs.service_repository_url}}
       working-directory: ${{inputs.service_dir}}
     - run: docker save ${{inputs.service_repository_url}} > image.tar
     - name: Upload artifact
       uses: actions/upload-artifact@v2
       with:
         name: ${{inputs.artifact_name}}
         path: image.tar
