spring:
  application:
    name: orchestration
server:
  port: 80
eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: "/actuator/health"
zuul:
  ignored-services: '*'
  routes:
    account-management:
      path: "/api/v1/oauth/*"
      strip-prefix: false
