on: [push]
jobs:
  call-maven-build:
    uses: csum112/oha/.github/workflows/maven_build.yml@pipelines
    with:
      service_dir: orchestration-service
      service_repository_url: 550479832263.dkr.ecr.eu-west-1.amazonaws.com/orchestration-service-bar
      artifact_name: orchestration-service-image
  call-deploy-build:
    needs: call-maven-build
    uses: csum112/oha/.github/workflows/deploy.yml@pipelines
    with:
      artifact_name: orchestration-service-image
      service_name: orchestration-service
      cluster_name: smpip-cluster
    secrets:
      service_repository_url: 550479832263.dkr.ecr.eu-west-1.amazonaws.com/orchestration-service-bar
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  call-npm-build:
    uses: csum112/oha/.github/workflows/npm_build.yml@pipelines
    with:
      service_dir: social-media-post-impact-prediction-ui
      service_repository_url: 550479832263.dkr.ecr.eu-west-3.amazonaws.com/ui-core-service-bar
      artifact_name: ui-service-image
  call-npm-deploy:
    needs: call-npm-build
    uses: csum112/oha/.github/workflows/deploy.yml@pipelines
    with:
      artifact_name: ui-service-image
      service_name: ui-core-service
      cluster_name: smpip-cluster
    secrets:
      service_repository_url: 550479832263.dkr.ecr.eu-west-3.amazonaws.com/ui-core-service-bar
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
#  call-npm-build:
#      uses: csum112/oha/.github/workflows/npm_build.yml@pipelines
#      with:
#        service_dir: social-media-post-impact-prediction-ui
#        service_repository_url: https://google.com
#  call-python-build:
#      uses: csum112/oha/.github/workflows/python_build.yml@pipelines
#      with:
#        service_dir: prediction
#        service_repository_url: https://google.com
